server:
  port: ${vcap.application.port:8999}




spring:
  profiles: default

  mail:
    host: smtp.gmail.com
    port: 465
    sender: campus@joedayz.pe
    username: campus@joedayz.pe
    password: ArrozConAngular2
    fromIP: campus.joedayz.pe

  datasource:
    url: jdbc:mysql://localhost/api
    username: root
    password: joedayz
    testOnBorrow: true
    removeAbandonedTimeout: 1800
    removeAbandoned: true
    validationQuery: SELECT 1 FROM DUAL
    logAbandoned: true
    minEvictableIdleTimeMillis: 60000
    defaultReadOnly: false
    maxWait: 60000
    maxIdle: 1
    minIdle: 0
    maxActive: 50
    initialSize: 1

  jpa:
    #database-platform: org.hibernate.dialect.Oracle10gDialect
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    #generate-ddl= true.hibernate.ejb.interceptor=MyInterceptorClassName

    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.DefaultNamingStrategy



    properties:
      hibernate:
          ejb:
            interceptor: pe.joedayz.api.jpa.ApiEntityInterceptorImpl
          jdbc:
            batch_size: 20


---
spring:
  profiles: joeint

  mail:
    host: smtp.gmail.com
    port: 465
    sender: campus@joedayz.pe
    username: campus@joedayz.pe
    password: ArrozConAngular2
    fromIP: campus.joedayz.pe

  datasource:
    url: jdbc:mysql://localhost/joecampus_api
    username: joecampus_api
    password: Dr3cVhcAB!d#6WqU
    testOnBorrow: true
    removeAbandonedTimeout: 1800
    removeAbandoned: true
    validationQuery: SELECT 1 FROM DUAL
    logAbandoned: true
    minEvictableIdleTimeMillis: 60000
    defaultReadOnly: false
    maxWait: 60000
    maxIdle: 1
    minIdle: 0
    maxActive: 50
    initialSize: 1

  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true

    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.DefaultNamingStrategy



    properties:
      hibernate:
          ejb:
            interceptor: pe.joedayz.api.jpa.ApiEntityInterceptorImpl
          jdbc:
            batch_size: 20